export const cookies = [
  {
    name: "Necessary / Essential Cookies",
    type: "Persistent Cookies",
    admin: "Us",
    purpose:
      "These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.",
  },
  {
    name: "Cookies Policy / Notice Acceptance Cookies",
    type: "Persistent Cookies",
    admin: "Us",
    purpose:
      "These Cookies identify if users have accepted the use of cookies on the Website.",
  },
  {
    name: "Functionality Cookies",
    type: "Persistent Cookies",
    admin: "Us",
    purpose:
      "These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website.",
  },
  {
    name: "Tracking and Performance Cookies",
    type: "Persistent Cookies",
    admin: "Us",
    purpose:
      "These Cookies are used to track information about traffic to the Website and how users use the Website. The information gathered via these Cookies may directly or indirectly identify you as an individual visitor. This is because the information collected is typically linked to a pseudonymous identifier associated with the device you use to access the Website. We may also use these Cookies to test new advertisements, pages, features or new functionality of the Website to see how our users react to them.",
  },
];

export const lists = {
  definitions: [
    {
      strong: "You",
      text: " means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable. Under GDPR (General Data Protection Regulation), You can be referred to as the Data Subject or as the User as you are the individual using the Service.",
    },
    {
      strong: "Company",
      text: " (referred to as either “the Company”, “We”, “Us” or “Our” in this Agreement) refers to Live Fully Coaching, Ruská 8, Praha 10-Vrsovice, Praha. For the purpose of the GDPR, the Company is the Data Controller.",
    },
    {
      strong: "Affiliate",
      text: " means an entity that controls, is controlled by or is under common control with a party, where “control” means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.",
    },
    {
      strong: "Account",
      text: " means a unique account created for You to access our Service or parts of our Service.",
    },
    {
      strong: "Website",
      text: " refers to the website accessible at livefullycoaching.com",
    },
    { strong: "Service", text: " refers to the Website." },
    { strong: "Country", text: " refers to Czechia" },
    {
      strong: "Service Provider",
      text: " means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.",
    },
    {
      strong: "Third-party Social Media Service",
      text: " refers to any website or any social network website through which a User can log in or create an account to use the Service.",
    },
    {
      strong: "Facebook Fan Page",
      text: " is a public profile named Sean Coley – Transformation Coach specifically created by the Company on the Facebook social network, accessible from https://www.facebook.com/livefullycoaching",
    },
    {
      strong: "Personal Data",
      text: " is any information that relates to an identified or identifiable individual.",
    },
    {
      strong: "Cookies",
      text: " are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.",
    },
    {
      strong: "Usage Data",
      text: " refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).",
    },
    {
      strong: "Data Controller",
      text: ", for the purposes of the GDPR (General Data Protection Regulation), refers to the Company as the legal person which alone or jointly with others determines the purposes and means of the processing of Personal Data.",
    },
  ],
  dataUsage: [
    {
      strong: "To provide and maintain our Service",
      text: ", including to monitor the usage of our Service.",
    },
    {
      strong: "To manage Your Account:",
      text: " to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.",
    },
    {
      strong: "For the performance of a contract:",
      text: " the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.",
    },
    {
      strong: "To contact You:",
      text: " To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application’s push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.",
    },
    {
      strong: "To provide You",
      text: " with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.",
    },
    {
      strong: "To manage Your requests:",
      text: " To attend and manage Your requests to Us.",
    },
  ],
  dataSharing: [
    {
      strong: "With Service Providers:",
      text: " We may share Your personal information with Service Providers to monitor and analyze the use of our Service, to show advertisements to You to help support and maintain Our Service, to contact You, to advertise on third party websites to You after You visited our Service or for payment processing.",
    },
    {
      strong: "For Business transfers:",
      text: " We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of our business to another company.",
    },
    {
      strong: "With Affiliates:",
      text: " We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us.",
    },
    {
      strong: "With Business partners:",
      text: " We may share Your information with Our business partners to offer You certain products, services or promotions.",
    },
    {
      strong: "With other users:",
      text: " when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside. If You interact with other users or register through a Third-Party Social Media Service, Your contacts on the Third-Party Social Media Service may see You name, profile, pictures and description of Your activity. Similarly, other users will be able to view descriptions of Your activity, communicate with You and view Your profile.",
    },
  ],
  otherLegalReqs: [
    "Comply with a legal obligation",
    "Protect and defend the rights or property of the Company",
    "Prevent or investigate possible wrongdoing in connection with the Service",
    "Protect the personal safety of Users of the Service or the public",
    "Protect against legal liability",
  ],
  serviceProviders: [
    {
      type: "Analytics",
      preamble:
        "We may use third-party Service providers to monitor and analyze the use of our Service.",
      providers: ["Google analytics"],
      postamble: ["Google Analytics is a web analytics service."],
      linkUrl: "https://policies.google.com/technologies/partner-sites",
    },
    {
      type: "Email Marketing",
      preamble:
        "We may use Your Personal Data to contact You with newsletters, marketing or promotional materials and other information that may be of interest to You. You may opt-out of receiving any, or all, of these communications from Us by following the unsubscribe link or instructions provided in any email We send or by contacting Us. We may use Email Marketing Service Providers to manage and send emails to You.",
      providers: ["Active Campaign"],
      postamble: ["Active Campaign is an email automation software."],
      linkUrl: "https://www.activecampaign.com/legal/privacy-policy",
    },
  ],
  gdpr: {
    legalBasis: [
      {
        strong: "Consent:",
        text: " You have given Your consent for processing Personal Data for one or more specific purposes.",
      },
      {
        strong: "Performance of a contract:",
        text: " Provision of Personal Data is necessary for the performance of an agreement with You and/or for any pre-contractual obligations thereof.",
      },
      {
        strong: "Legal obligations:",
        text: " Processing Personal Data is necessary for compliance with a legal obligation to which the Company is subject.",
      },
      {
        strong: "Vital interests:",
        text: " Processing Personal Data is necessary in order to protect Your vital interests or of another natural person.",
      },
      {
        strong: "Public interests:",
        text: " Processing Personal Data is related to a task that is carried out in the public interest or in the exercise of official authority vested in the Company.",
      },
      {
        strong: "Legitimate interests:",
        text: " Processing Personal Data is necessary for the purposes of the legitimate interests pursued by the Company.",
      },
    ],
    rights: [
      {
        strong: "Request access to Your Personal Data.",
        text: " The right to access, update or delete the information We have on You. Whenever made possible, you can access, update or request deletion of Your Personal Data directly within Your account settings section. If you are unable to perform these actions yourself, please contact Us to assist You. This also enables You to receive a copy of the Personal Data We hold about You.",
      },
      {
        strong:
          "Request correction of the Personal Data that We hold about You.",
        text: " You have the right to to have any incomplete or inaccurate information We hold about You corrected.",
      },
      {
        strong: "Object to processing of Your Personal Data.",
        text: " This right exists where We are relying on a legitimate interest as the legal basis for Our processing and there is something about Your particular situation, which makes You want to object to our processing of Your Personal Data on this ground. You also have the right to object where We are processing Your Personal Data for direct marketing purposes.",
      },
      {
        strong: "Request erasure of Your Personal Data.",
        text: " You have the right to ask Us to delete or remove Personal Data when there is no good reason for Us to continue processing it.",
      },
      {
        strong: "Request the transfer of Your Personal Data.",
        text: " We will provide to You, or to a third-party You have chosen, Your Personal Data in a structured, commonly used, machine-readable format. Please note that this right only applies to automated information which You initially provided consent for Us to use or where We used the information to perform a contract with You.",
      },
      {
        strong: "Withdraw Your consent.",
        text: " You have the right to withdraw Your consent on using your Personal Data. If You withdraw Your consent, We may not be able to provide You with access to certain specific functionalities of the Service.",
      },
    ],
  },
};
